set_property(GLOBAL PROPERTY TARGET_SUPPORTS_SHARED_LIBS TRUE)

set(CMAKE_SYSTEM_INCLUDE_PATH /include )
set(CMAKE_SYSTEM_LIBRARY_PATH /lib )
set(CMAKE_SYSTEM_PROGRAM_PATH /bin )

set(CMAKE_STATIC_LIBRARY_PREFIX "lib")
set(CMAKE_STATIC_LIBRARY_SUFFIX ".a")
set(CMAKE_SHARED_LIBRARY_PREFIX "")
set(CMAKE_SHARED_LIBRARY_SUFFIX ".kx")
set(CMAKE_LINK_LIBRARY_SUFFIX ".a")
set(CMAKE_EXECUTABLE_SUFFIX "")
