#
# Toolchain script for PbOS kernel components on x86_64.
#
# Copyright (C) 2022 PbOS Contributors
#
list(PREPEND CMAKE_MODULE_PATH "${CMAKE_CURRENT_LIST_DIR}/../")
set(CMAKE_SYSTEM_NAME PbOSKernel)
set(CMAKE_SYSTEM_PROCESSOR x86_64)

set_property(GLOBAL PROPERTY CMAKE_CROSSCOMPILING TRUE)

set(CMAKE_TRY_COMPILE_TARGET_TYPE STATIC_LIBRARY)

find_program(CMAKE_AR NAMES ar llvm-ar REQUIRED)
find_program(CMAKE_LINKER NAMES gold ld ld.lld REQUIRED)
find_program(CMAKE_OBJCOPY NAMES objcopy llvm-objcopy REQUIRED)
find_program(CMAKE_RANLIB NAMES ranlib llvm-ranlib REQUIRED)
find_program(CMAKE_SIZE NAMES size llvm-size REQUIRED)
find_program(CMAKE_STRIP NAMES strip llvm-strip REQUIRED)

set(CMAKE_LINK_DEF_FILE_FLAG "")
set(CMAKE_EXE_LINK_FLAGS "")

set(CMAKE_FIND_ROOT_PATH ${CMAKE_CURRENT_SOURCE_DIR}/..)

set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE BOTH)

include(CMakeSystemSpecificInformation)

if(CMAKE_HOST_WIN32)
	include(Platform/WindowsPaths)
elseif(CMAKE_HOST_UNIX)
	include(Platform/UnixPaths)
endif()

#
# C setup
#
set(C_STANDARD 99)
find_program(CMAKE_C_COMPILER NAMES gcc clang REQUIRED)
set(CMAKE_C_COMPILER_TARGET x86_64-elf)

set(CMAKE_C_FLAGS "-fvisibility=hidden -m64 -nostdlib -fno-stack-protector -mno-stack-arg-probe -mno-red-zone -mno-mmx -mno-sse -fno-builtin -ffreestanding -fPIE")
set(CMAKE_C_FLAGS_DEBUG "-O0 -g")
set(CMAKE_C_FLAGS_RELWITHDBGINFO "-O2 -g")
set(CMAKE_C_FLAGS_RELEASE "-O2")
set(CMAKE_C_FLAGS_MINSIZEREL "-Os")

set(CMAKE_C_LINK_FLAGS "-m elf_x86_64 -pie --export-dynamic")
set(CMAKE_C_COMPILE_OBJECT "<CMAKE_C_COMPILER> <DEFINES> <INCLUDES> <FLAGS> -o <OBJECT> -c <SOURCE>")
set(CMAKE_C_LINK_EXECUTABLE "<CMAKE_LINKER> <LINK_FLAGS> <CMAKE_C_LINK_FLAGS> <OBJECTS> -o <TARGET> <LINK_LIBRARIES>")
set(CMAKE_C_CREATE_SHARED_LIBRARY "<CMAKE_LINKER> <LINK_FLAGS> <CMAKE_C_LINK_FLAGS> <OBJECTS> -o <TARGET> <LINK_LIBRARIES> -shared")

#
# C++ setup
#
set(CXX_STANDARD 20)
set(CMAKE_CXX_STANDARD_REQUIRED ON)
set(CMAKE_CXX_EXTENSIONS OFF)
find_program(CMAKE_CXX_COMPILER NAMES g++ clang++ REQUIRED)
set(CMAKE_CXX_COMPILER_TARGET x86_64-elf)

set(CMAKE_CXX_FLAGS "-fvisibility=hidden -m64 -nostdlib -fno-stack-protector -fno-exceptions -fno-rtti -fno-use-cxa-atexit -mno-stack-arg-probe -mno-red-zone -mno-mmx -mno-sse -fno-builtin -ffreestanding -fPIE")
set(CMAKE_CXX_FLAGS_DEBUG "-O0 -g")
set(CMAKE_CXX_FLAGS_RELWITHDBGINFO "-O2 -g")
set(CMAKE_CXX_FLAGS_RELEASE "-O2")
set(CMAKE_CXX_FLAGS_MINSIZEREL "-Os")

set(CMAKE_CXX_LINK_FLAGS "-m elf_x86_64 -pie --export-dynamic")
set(CMAKE_CXX_COMPILE_OBJECT "<CMAKE_CXX_COMPILER> <DEFINES> <INCLUDES> <FLAGS> -o <OBJECT> -c <SOURCE>")
set(CMAKE_CXX_LINK_EXECUTABLE "<CMAKE_LINKER> <LINK_FLAGS> <CMAKE_CXX_LINK_FLAGS> <OBJECTS> -o <TARGET> <LINK_LIBRARIES>")
set(CMAKE_CXX_CREATE_SHARED_LIBRARY "<CMAKE_LINKER> <LINK_FLAGS> <CMAKE_CXX_LINK_FLAGS> <OBJECTS> -o <TARGET> <LINK_LIBRARIES> -shared")

#
# Assembly setup
#
find_program(CMAKE_ASM_COMPILER NAMES as clang gcc REQUIRED)
set(CMAKE_ASM_COMPILER_TARGET x86_64-elf)

set(CMAKE_ASM_FLAGS_DEBUG "-O0 -g")
set(CMAKE_ASM_FLAGS_RELWITHDBGINFO "-O2 -g")
set(CMAKE_ASM_FLAGS_RELEASE "-O2")
set(CMAKE_ASM_FLAGS_MINSIZEREL "-Os")

set(CMAKE_ASM_LINK_FLAGS "-m elf_x86_64 -pie --export-dynamic")
set(CMAKE_ASM_COMPILE_OBJECT "<CMAKE_ASM_COMPILER> <DEFINES> <INCLUDES> <FLAGS> -o <OBJECT> -c <SOURCE>")
set(CMAKE_ASM_LINK_EXECUTABLE "<CMAKE_LINKER> <LINK_FLAGS> <CMAKE_ASM_LINK_FLAGS> <OBJECTS> -o <TARGET> <LINK_LIBRARIES>")
set(CMAKE_ASM_CREATE_SHARED_LIBRARY "<CMAKE_LINKER> <LINK_FLAGS> <CMAKE_ASM_LINK_FLAGS> <OBJECTS> -o <TARGET> <LINK_LIBRARIES> -shared")
