#ifndef _FREESTDC_COMMON_FORMAT_H_
#define _FREESTDC_COMMON_FORMAT_H_

#include <stddef.h>
#include <stdint.h>

enum {
	FMTCTL_FLAGS_NONE,
	FMTCTL_FLAGS_RIGHT_ALIGN,
	FMTCTL_FLAGS_DISPLAY_POSITIVE,
	FMTCTL_FLAGS_SPECIAL_OUTPUT,
	FMTCTL_FLAGS_PADDING_WITH_0
};

enum {
	FMTCTL_LENGTH_NONE,
	FMTCTL_LENGTH_HALF,
	FMTCTL_LENGTH_LONG,
	FMTCTL_LENGTH_LONG_FLOAT
};

enum {
	FMTCTL_SPECIFIER_DEC,
	FMTCTL_SPECIFIER_OCT,
	FMTCTL_SPECIFIER_HEX,
	FMTCTL_SPECIFIER_UNSIGNED,
	FMTCTL_SPECIFIER_FLOAT,
	FMTCTL_SPECIFIER_FLOAT_EXPONENTIAL,
	FMTCTL_SPECIFIER_FLOAT_TRIMMED,
	FMTCTL_SPECIFIER_CHAR,
	FMTCTL_SPECIFIER_STR,
	FMTCTL_SPECIFIER_PTR,
	FMTCTL_SPECIFIER_LUNSIGNED,
	FMTCTL_SPECIFIER_LLUNSIGNED,
	FMTCTL_SPECIFIER_PERCENT
};

typedef struct _fmtctl_info_t {
	uint8_t flags;
	int width;
	int precision;
	uint8_t length;
	uint8_t specifier;
} fmtctl_info_t;

size_t fmtctl_parse(const char *str, fmtctl_info_t *dest);

#endif
