#ifndef _PBOS_KF_BASEDEFS_H_
#define _PBOS_KF_BASEDEFS_H_

#include <pbos/common.h>

#if PBOS_COMPILING_KERNEL
	#define PBOS_KERNEL_PUBLIC PBOS_EXPORTED
#else
	#define PBOS_KERNEL_PUBLIC PBOS_IMPORTED
#endif
#define PBOS_KERNEL_PRIVATE

#define PBOS_MODULE_PUBLIC PBOS_EXPORTED
#define PBOS_MODULE_PRIVATE

#endif
